# Generated by Django 3.2.3 on 2021-07-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Notic: This name will show publicaly', max_length=50)),
                ('feedback', models.TextField(max_length=500)),
            ],
        ),
    ]
