# Generated by Django 3.2.3 on 2021-07-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0022_auto_20210727_0454'),
        ('Feedback', '0002_userfeedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EshopApp.siteinfo'),
            preserve_default=False,
        ),
    ]
