# Generated by Django 3.2.3 on 2021-07-27 04:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0004_auto_20210726_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(default='1920x750', editable=False, help_text='1920x900, recomended resolution', max_length=50)),
                ('image', models.ImageField(help_text='recomended resolution - 1920x900', upload_to='site_config_img/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(help_text='Write title of offer. Ex- Latest Update Brand', max_length=100)),
                ('offer', models.CharField(help_text='What is your offer. Ex- 40%/ of on Electronic ', max_length=100)),
                ('offer_desc', models.CharField(help_text='Discribe the offer for best understating.', max_length=100)),
                ('offer_start_at', models.IntegerField(help_text='Write offer stating price')),
                ('resolution', models.CharField(default='1920x900', editable=False, max_length=50)),
                ('image', models.ImageField(help_text='recomended resolution - 1920x900', upload_to='site_config_img/images/')),
                ('is_blog', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='site_info_img_content',
            name='site_info_img',
        ),
        migrations.AlterField(
            model_name='contact_us_info',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 39, 41, 905660)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 39, 41, 899151)),
        ),
        migrations.DeleteModel(
            name='site_info_img',
        ),
        migrations.DeleteModel(
            name='site_info_img_content',
        ),
        migrations.AddField(
            model_name='slider',
            name='site_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EshopApp.siteinfo'),
        ),
        migrations.AddField(
            model_name='backgroundbanner',
            name='site_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EshopApp.siteinfo'),
        ),
    ]
