# Generated by Django 3.2.3 on 2021-07-27 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0005_auto_20210726_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('at_date_time', models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 41, 49, 400409))),
                ('contact_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EshopApp.contactus')),
            ],
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 41, 49, 393899)),
        ),
        migrations.DeleteModel(
            name='contact_us_info',
        ),
    ]
