# Generated by Django 3.2.3 on 2021-07-27 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0006_auto_20210726_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 51, 46, 109319)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 51, 46, 109319)),
        ),
        migrations.AlterField(
            model_name='siteoffer',
            name='offer_name',
            field=models.CharField(help_text="Ex- Official Launch Don't miss", max_length=100),
        ),
        migrations.AlterField(
            model_name='siteoffer',
            name='offer_title',
            field=models.CharField(help_text='Ex - Globle Offer', max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='offer_start_at',
            field=models.FloatField(help_text='Write offer stating price'),
        ),
    ]
