# Generated by Django 3.2.3 on 2021-07-27 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0007_auto_20210726_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 22, 0, 17, 148796)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 22, 0, 17, 133205)),
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(default='760x800', editable=False, help_text='760x800, recomended resolution', max_length=50)),
                ('image', models.ImageField(help_text='recomended resolution - 1920x900', upload_to='site_config_img/images/')),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EshopApp.siteinfo')),
            ],
        ),
    ]
