# Generated by Django 3.2.3 on 2021-07-27 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0008_auto_20210726_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 20, 29, 701060)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 20, 29, 687070)),
        ),
    ]
