# Generated by Django 3.2.3 on 2021-07-27 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0009_auto_20210726_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqinfo',
            old_name='title',
            new_name='faq_title',
        ),
        migrations.RenameField(
            model_name='sitefaq',
            old_name='Faq_title',
            new_name='faqInfo',
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 23, 43, 851136)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 23, 43, 839140)),
        ),
    ]
