# Generated by Django 3.2.3 on 2021-07-27 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0010_auto_20210726_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitefaq',
            name='faqInfo',
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 37, 48, 609023)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 37, 48, 597033)),
        ),
    ]
