# Generated by Django 3.2.3 on 2021-07-27 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0012_auto_20210726_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteFaq',
            new_name='Faq',
        ),
        migrations.RenameModel(
            old_name='FaqInfo',
            new_name='TitleOfFaq',
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 46, 21, 709170)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 46, 21, 697168)),
        ),
    ]
