# Generated by Django 3.2.3 on 2021-07-27 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0013_auto_20210726_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titleoffaq',
            old_name='faq_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 48, 0, 145056)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 48, 0, 137055)),
        ),
    ]
