# Generated by Django 3.2.3 on 2021-07-27 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0023_auto_20210727_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='resolution',
            field=models.CharField(default='1920x750', help_text='1920x750, recomended resolution', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 7, 30, 10, 987146)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 7, 30, 10, 981146)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='resolution',
            field=models.CharField(default='1920x900', max_length=50),
        ),
    ]
