# Generated by Django 3.2.3 on 2021-08-27 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0024_auto_20210727_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 2, 25, 0, 105272)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 2, 25, 0, 89651)),
        ),
        migrations.CreateModel(
            name='ShopByDealsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_config_img/shop_by_deals/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EshopApp.siteinfo')),
            ],
        ),
    ]
