# Generated by Django 3.2.3 on 2021-11-06 16:23

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0026_auto_20210827_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsite',
            options={'verbose_name_plural': 'About Site'},
        ),
        migrations.AlterModelOptions(
            name='backgroundbanner',
            options={'verbose_name_plural': 'BG Banner'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='contactusinfo',
            options={'verbose_name_plural': 'ContactUs Info'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'News Letter'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'Site Info'},
        ),
        migrations.AlterModelOptions(
            name='siteoffer',
            options={'verbose_name_plural': 'Site Offer'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='titleoffaq',
            options={'verbose_name_plural': 'FAQ Title'},
        ),
        migrations.AlterField(
            model_name='aboutsite',
            name='discription',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 23, 3, 149908)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 23, 3, 134285)),
        ),
    ]
