# Generated by Django 3.2.3 on 2021-11-06 16:30

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0027_auto_20211106_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleoffaq',
            name='title',
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 30, 10, 715215)),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 30, 10, 699590)),
        ),
        migrations.AlterField(
            model_name='titleoffaq',
            name='discription',
            field=tinymce.models.HTMLField(),
        ),
    ]
