# Generated by Django 3.2.3 on 2021-11-06 16:35

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0028_auto_20211106_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 35, 22, 974522)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(help_text='Please write suitable answer..', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 35, 22, 958895)),
        ),
    ]
