# Generated by Django 3.2.3 on 2021-11-06 16:44

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('EshopApp', '0030_auto_20211106_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusinfo',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 44, 54, 710104)),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='change_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 44, 54, 705109)),
        ),
    ]
