# Generated by Django 3.2.3 on 2021-07-27 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210726_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 5, 7, 342520)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 5, 7, 344522)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='reply_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 5, 7, 345521)),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 5, 7, 345521)),
        ),
        migrations.AlterField(
            model_name='subcommentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 5, 7, 346520)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 5, 7, 343525)),
        ),
    ]
