# Generated by Django 3.2.3 on 2021-09-03 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210726_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 3, 54, 52, 326762)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 3, 54, 52, 326762)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='reply_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 3, 54, 52, 326762)),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 3, 54, 52, 326762)),
        ),
        migrations.AlterField(
            model_name='subcommentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 3, 54, 52, 326762)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 3, 54, 52, 326762)),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
