# Generated by Django 3.2.3 on 2021-09-08 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210907_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.AlterField(
            model_name='blog',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 20, 34, 155060)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 20, 34, 155060)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='reply_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 20, 34, 155060)),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 20, 34, 155060)),
        ),
        migrations.AlterField(
            model_name='subcommentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 20, 34, 155060)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 20, 34, 155060)),
        ),
    ]
