# Generated by Django 3.2.3 on 2021-09-08 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20210907_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='blogs.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 8, 8, 49, 955688)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 8, 8, 49, 971325)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='reply_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 8, 8, 49, 971325)),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 8, 8, 49, 971325)),
        ),
        migrations.AlterField(
            model_name='subcommentvote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 8, 8, 49, 971325)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 8, 8, 49, 971325)),
        ),
    ]
