# Generated by Django 3.2.3 on 2021-07-27 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210726_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 21, 5, 7, 327441), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 5, 7, 329438)),
        ),
    ]
