# Generated by Django 3.2.3 on 2021-07-27 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210726_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, help_text='https:/facebook.com/(USER_ID) - Put only your USER_ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, help_text='https:/instagram.com/(USER_ID) - Put only your USER_ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, help_text='https:/linkedin.com/(USER_ID) - Put only your USER_ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, help_text='https:/twitter.com/(USER_ID) - Put only your USER_ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 27, 5, 27, 11, 309130), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 5, 27, 11, 313172)),
        ),
    ]
