# Generated by Django 3.2.3 on 2021-07-27 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210727_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 27, 6, 26, 9, 631102), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.CharField(default='#', help_text='https:/facebook.com/(USER_ID) - Put only your USER_ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(default='#', help_text='https:/instagram.com/(USER_ID) - Put only your USER_ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(default='#', help_text='https:/linkedin.com/(USER_ID) - Put only your USER_ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 6, 26, 9, 635102)),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(default='#', help_text='https:/twitter.com/(USER_ID) - Put only your USER_ID', max_length=100),
        ),
    ]
