# Generated by Django 3.2.3 on 2021-07-28 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210727_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='is_shipping_details',
            field=models.BooleanField(default=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='is_billing_details',
            field=models.BooleanField(default=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 27, 21, 44, 27, 925881), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 21, 44, 27, 928876)),
        ),
    ]
