from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name="index"),
    path('productDetails/<int:product_id>',views.productDetails,name='productDetails'),
    path('shop/',views.shop,name='shop'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('checkout-all/',views.checkoutAll,name='checkout all'),
    path('checkout/<int:pid>',views.checkout,name='checkout'),
    path('checkout/<int:pid>/<int:qty>',views.checkoutQty,name='checkout Qty'),
    path('place-order/',views.orderPlace),
    path('add-more-order/',views.addMoreOrder),
    path('faq/',views.faq,name='faq'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('pnf404/',views.pnf404,name='pnf404'),
    path('about/',views.about,name='about'),
    path('cart/',views.cart,name='cart'),
    path('empty-blog/',views.emptyBlog,name='empty-blog'),
    # path('emptyWishlist/',views.emptyWishlist,name='empty-wishlist'),
    path('emptySearch/',views.emptySearch,name='empty-searc'),
    path('remove-my-tag/',views.removeTag,name='remove tag'),
    path('add-new-tag/',views.addNewTag,name='new tag adding'),
    path('add-new-review/',views.addNewReview,name='new review adding'),
    path('remove-review/',views.removeReview,name='Review Removing'),
    path('remove-review/',views.removeReview,name='Review Removing'),
    path("vote-for-review/",views.voteForReview,name='voting for review'),
    path("update-review/",views.updateReview,name='update review'),
    path('sort-review/',views.sortReview,name='review-sorting'),
    path('fetch-more-review/',views.fetchMoreReview,name='review getting one by one'),
    path('more-new-arrival-product/',views.fetchMoreNewArrivalProduct,name='product getting one by one'),
    path("product-viewer/",views.setHostnameIP,name='hostname and ip set on product viewer'),
    path("items-query/",views.query,name='user query'),
    path("return-my-order/<str:slug>",views.returnOrder,name='return order'),
    path("cancel-my-order/<str:slug>",views.cancelOrder,name='order cancellation'),
    path("genrate-invoice/<str:slug>",views.genrate_invoice),
]