# Generated by Django 3.2.3 on 2021-07-26 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcategory',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 52, 27, 59263)),
        ),
        migrations.AlterField(
            model_name='clickproduct',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 52, 27, 59263)),
        ),
        migrations.AlterField(
            model_name='clicksubcategory',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 52, 27, 59263)),
        ),
        migrations.AlterField(
            model_name='recentquery',
            name='query_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 52, 27, 59263)),
        ),
    ]
