# Generated by Django 3.2.3 on 2021-07-26 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tracking', '0002_auto_20210726_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcategory',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 54, 7, 483505)),
        ),
        migrations.AlterField(
            model_name='clickproduct',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 54, 7, 483505)),
        ),
        migrations.AlterField(
            model_name='clicksubcategory',
            name='at_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 54, 7, 483505)),
        ),
        migrations.AlterField(
            model_name='recentquery',
            name='query_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 54, 7, 467864)),
        ),
    ]
