# Generated by Django 3.2.3 on 2021-07-30 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0004_auto_20210726_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Ex - ELECTRONICS, SPORTS, MEDICINE more', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 0, 30, 50, 36365)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 0, 30, 50, 34368)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 0, 30, 50, 37364)),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling_product.category')),
            ],
        ),
    ]
