# Generated by Django 3.2.3 on 2021-08-01 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0007_auto_20210730_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 9, 14, 49, 968793)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 9, 14, 49, 966794)),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 9, 14, 49, 968793)),
        ),
    ]
