# Generated by Django 3.2.3 on 2021-08-02 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0010_auto_20210801_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 23, 8, 477208)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 23, 8, 477208)),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_charge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 23, 8, 477208)),
        ),
    ]
