# Generated by Django 3.2.3 on 2021-08-02 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0011_auto_20210801_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_limit',
        ),
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.CharField(choices=[('', 'SELECT OFFER'), ('YES', 'YES'), ('NO', 'NO')], default='SELECT OFFER', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 32, 21, 364712)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 32, 21, 364712)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 32, 21, 372712)),
        ),
    ]
