# Generated by Django 3.2.3 on 2021-08-02 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0012_auto_20210801_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='no weight', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 23, 27, 28, 851308)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 23, 27, 28, 851308)),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='no size', max_length=50),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 23, 27, 28, 851308)),
        ),
    ]
