# Generated by Django 3.2.3 on 2021-08-02 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0014_auto_20210801_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img.png', upload_to='product_manage_img/product_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 23, 57, 9, 77247)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 23, 57, 9, 77247)),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img_path',
            field=models.ImageField(upload_to='product_manage_img/product_images/'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 23, 57, 9, 77247)),
        ),
    ]
