# Generated by Django 3.2.3 on 2021-08-03 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0015_auto_20210801_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='category',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='selling_product.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 33, 54, 964380)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 33, 54, 962381)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 33, 54, 964380)),
        ),
    ]
