# Generated by Django 3.2.3 on 2021-08-03 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0016_auto_20210802_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='cateogry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='selling_product.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 42, 35, 116273)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 42, 35, 114274)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 42, 35, 116273)),
        ),
    ]
