# Generated by Django 3.2.3 on 2021-08-03 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0017_auto_20210802_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrand',
            old_name='cateogry',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 44, 3, 826551)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 44, 3, 824554)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 23, 44, 3, 827551)),
        ),
    ]
