# Generated by Django 3.2.3 on 2021-08-10 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0019_auto_20210810_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='usr',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 9, 38, 3299)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 9, 38, 1255)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 9, 38, 3299)),
        ),
    ]
