# Generated by Django 3.2.3 on 2021-08-10 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0021_auto_20210810_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='usr',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 38, 34, 104140)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 38, 34, 101144)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 38, 34, 106139)),
        ),
    ]
