# Generated by Django 3.2.3 on 2021-08-11 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0025_auto_20210811_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_info',
            field=models.TextField(default='color:red blue,weight:10gm', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 3, 17, 37, 773395)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 3, 17, 37, 771397)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 3, 17, 37, 773395)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 3, 17, 37, 775392)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 3, 17, 37, 774393)),
        ),
    ]
