# Generated by Django 3.2.3 on 2021-08-13 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0028_auto_20210812_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewvote',
            old_name='is_like',
            new_name='is_up_vote',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 23, 37, 26, 284308)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 23, 37, 26, 280305)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 23, 37, 26, 286307)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 23, 37, 26, 290306)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 23, 37, 26, 288307)),
        ),
    ]
