# Generated by Django 3.2.3 on 2021-08-20 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0033_auto_20210815_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selled_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 0, 13, 35, 697120)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 0, 13, 35, 697120)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 0, 13, 35, 697120)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 0, 13, 35, 697120)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 0, 13, 35, 697120)),
        ),
    ]
