# Generated by Django 3.2.3 on 2021-08-24 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0035_auto_20210820_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='m_r_p',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 3, 10, 48, 44576)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 3, 10, 48, 44576)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 3, 10, 48, 44576)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 3, 10, 48, 60196)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 3, 10, 48, 60196)),
        ),
    ]
