# Generated by Django 3.2.3 on 2021-11-05 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0040_auto_20211105_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='how_many',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 30, 19, 950650)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 30, 19, 946655)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 30, 19, 951648)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 30, 19, 952650)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 30, 19, 952650)),
        ),
    ]
