# Generated by Django 3.2.3 on 2021-11-05 17:56

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0042_auto_20211105_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='disc',
            field=tinymce.models.HTMLField(default='MSG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 10, 55, 23, 987947)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 10, 55, 23, 987947)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 10, 55, 23, 987947)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 10, 55, 24, 3572)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 10, 55, 23, 987947)),
        ),
    ]
