# Generated by Django 3.2.3 on 2021-11-08 14:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0044_auto_20211106_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 6, 56, 15, 357353)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 6, 56, 15, 357353)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 6, 56, 15, 357353)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 6, 56, 15, 357353)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 6, 56, 15, 357353)),
        ),
    ]
