# Generated by Django 3.2.3 on 2021-11-08 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0045_auto_20211108_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='delevery_location',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='delevery_pin',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
        migrations.AddField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancle', 'Cancle')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 7, 23, 49, 927679), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 7, 23, 49, 927679)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 7, 23, 49, 927679)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 7, 23, 49, 927679)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 7, 23, 49, 927679)),
        ),
        migrations.CreateModel(
            name='order_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('langitude', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('leave_note', tinymce.models.HTMLField()),
                ('arrival_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('leaved_time', models.TimeField()),
                ('leaved_date', models.DateField()),
                ('tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling_product.checkout')),
            ],
        ),
    ]
