# Generated by Django 3.2.3 on 2021-11-08 16:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selling_product', '0050_auto_20211108_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.IntegerField()),
                ('pin_code', models.BigIntegerField()),
                ('full_address', tinymce.models.HTMLField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 18, 32, 762363), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 18, 32, 762363)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 18, 32, 762363)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 18, 32, 762363)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 18, 32, 762363)),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('langitude', models.CharField(max_length=100)),
                ('leave_note', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('arrived', 'Arrived'), ('deleverd', 'Deleverd')], default='arrived', max_length=50)),
                ('arrival_time', models.TimeField()),
                ('arrival_date', models.DateField(default=datetime.date.today)),
                ('leaved_time', models.TimeField()),
                ('leaved_date', models.DateField()),
                ('office_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling_product.office')),
                ('tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling_product.checkout')),
            ],
            options={
                'verbose_name_plural': 'Order Tracking',
            },
        ),
    ]
