# Generated by Django 3.2.3 on 2021-11-08 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0051_auto_20211108_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='leave_note',
        ),
        migrations.AddField(
            model_name='office',
            name='helpline_email',
            field=models.EmailField(default='satyamishra559@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='helpline_number',
            field=models.BigIntegerField(default=100333),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 21, 32, 753458), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 21, 32, 753458)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 21, 32, 753458)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 21, 32, 753458)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 21, 32, 753458)),
        ),
    ]
