# Generated by Django 3.2.3 on 2021-11-08 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0052_auto_20211108_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='langitude',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='latitude',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 24, 9, 492718), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 24, 9, 492718)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 24, 9, 492718)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 24, 9, 508334)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 24, 9, 508334)),
        ),
    ]
