# Generated by Django 3.2.3 on 2021-11-08 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0053_auto_20211108_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='price',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 50, 12, 616921), editable=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('arrived', 'Arrived'), ('dispatch', 'Dispatch'), ('cancel', 'Cancelled'), ('deliverd', 'Finally Deliverd')], default='arrived', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 50, 12, 616921)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 50, 12, 616921)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 50, 12, 616921)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 50, 12, 616921)),
        ),
    ]
