# Generated by Django 3.2.3 on 2021-11-08 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0054_auto_20211108_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='color',
            field=models.CharField(default='#ffff', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 33, 18, 668237), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 33, 18, 668237)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 33, 18, 668237)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 33, 18, 685159)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 33, 18, 668237)),
        ),
    ]
