# Generated by Django 3.2.3 on 2021-11-08 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211108_1046'),
        ('selling_product', '0056_auto_20211108_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='billing_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.billinginfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 46, 6, 563125), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 46, 6, 563125)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 46, 6, 563125)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 46, 6, 563125)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 10, 46, 6, 563125)),
        ),
    ]
