# Generated by Django 3.2.3 on 2021-11-11 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_product', '0058_auto_20211111_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutitemowner',
            old_name='owner',
            new_name='item_owner',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 7, 33, 0, 465918), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 7, 33, 0, 465918)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 7, 33, 0, 481543)),
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 7, 33, 0, 481543)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 7, 33, 0, 481543)),
        ),
    ]
